//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation_Suite.Configuration_Tier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class URLConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal URLConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automation_Suite.Configuration_Tier.URLConfig", typeof(URLConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://uatportalap.ncs.gov.ie/en/SignIn.
        /// </summary>
        public static string ApplicantPortal_TestURL {
            get {
                return ResourceManager.GetString("ApplicantPortal_TestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://eypuat.ncs.gov.ie/main.aspx#563241825.
        /// </summary>
        public static string CRM_SPP_Frame {
            get {
                return ResourceManager.GetString("CRM_SPP_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://preportalsp.ncs.gov.ie/.
        /// </summary>
        public static string PreProd_ServiceProviderPortal {
            get {
                return ResourceManager.GetString("PreProd_ServiceProviderPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://uatportalsp.ncs.gov.ie/.
        /// </summary>
        public static string TestURL_ServiceProviderPortal {
            get {
                return ResourceManager.GetString("TestURL_ServiceProviderPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://eypuat.ncs.gov.ie/main.aspx#838305666.
        /// </summary>
        public static string UAT_CRM {
            get {
                return ResourceManager.GetString("UAT_CRM", resourceCulture);
            }
        }
    }
}
